### PR TITLE
Update `tools m3connector create environment` command to upsert the `<env>-kafka-files` configmap

### PR DESCRIPTION
**Pull request by joelhoisko**
## Summary

- Made the `tools m3connector create environment` CLI command to also upsert the `<env>-kafka-files` configmap in the correct environment in k8s with the credentials, certificates and `config.json`
- Made the `CreateTopic()` & `AddACL()` methods in the `aiven` package to not return errors if the ACL/topic already existed.
- Changed the `CreateUser()` method to `GetOrCreateUser()` so that it doesn't fail if the user already exists
- Updated mocks with mockery 2.12.2 as the old ones didn't work with go 1.18

### CODE REVIEW

**Comment by joelhoisko** [comment]
## Testing

Did testing with the local k3d cluster and created some topics for the default application and dev environment we have in there.

1. Reset the local k3d cluster
2. Run this command with the args for the default customer/application we have configured in k3d:
```sh
go run main.go tools m3connector create environment --customer-id 453e04a7-4f9d-42f2-b36c-d51fa2c83fa3 --application-id 11b6cf47-5d9f-438f-8116-0d9828654657 --environment dev --aiven-project dolittle-test-env --aiven-service kafka-test-env --aiven-api-token <my-aive-api-token>
```
3. Check the aiven console that the topics etc had been created
4. Chech that the `dev-kafka-files` configmap is created with all of the good stuff in it:
```sh
kubectl -n application-11b6cf47-5d9f-438f-8116-0d9828654657 get cm dev-kafka-files -o yaml
```
5. Remove the `config.json` part from the `dev-kafka-files` and rerun the command to recreate it (testing that it not only creates a configmap but also updates it).

**Comment by joelhoisko** [comment]
Actually I found a bug with the created configmap not having the proper labels and annotations done so I'm gonna fix that real quick

**Comment by joelhoisko** [comment]
Bug fixed

**Review by jakhog — APPROVED** [review]
:shipit:

**Pull request merged**
